const ProductReviewsData = [
  {
    id: 1,
    username: "andybkohler",
    country: { name: "United Kingdom", code: "GB" },
    date: "8 months ago",
    rating: 5,
    review: "Good communication and great work.",
    productType: "enterprise",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/ca04c9a776fa3f9ffbeb0879d2091952-1707143072570/7d8006f9-c01f-44be-9158-86271b28e9d6.jpg",
    repeatClient: false,
  },
  {
    id: 2,
    username: "garethstageman",
    country: { name: "United States", code: "US" },
    date: "8 months ago",
    rating: 5,
    review:
      "We always use AutoBizz for our development work. Most of what we need is customized these days rather than standard gigs, and they always give us a fair quote, deliver fast and on time, and stand behind their work so we can be sure of ongoing support. Highly recommended.",
    productType: "inventory",
    image: "",
    repeatClient: false,
  },
  {
    id: 3,
    username: "andybkohler",
    country: { name: "United Kingdom", code: "GB" },
    date: "8 months ago",
    rating: 5,
    review: "Great work and great communication.",
    productType: "enterprise",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/ca04c9a776fa3f9ffbeb0879d2091952-1707143072570/7d8006f9-c01f-44be-9158-86271b28e9d6.jpg",
    repeatClient: false,
  },
  {
    id: 4,
    username: "garethstageman",
    country: { name: "United States", code: "US" },
    date: "10 months ago",
    rating: 5,
    review:
      "We have worked with AutoBizz IT team many times—they are always our go-to team whenever we need work of this type done. They are super responsive, very professional, friendly, and always get the job done very quickly. Highly recommended.",
    productType: "orders",
    image: "",
    repeatClient: false,
  },
  {
    id: 5,
    username: "investplan1952",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review:
      "I have worked with the AutoBizz team before, and their business savvy, knowledge, and professionalism continue their trend of never disappointing. I highly recommend them!",
    productType: "enterprise",
    image: "",
    repeatClient: true,
  },
  {
    id: 6,
    username: "investplan1952",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review:
      "I am beyond thrilled and incredibly impressed!  AutoBizz  over-delivered. They are professionals, experts, knowledgeable, and sophisticated, offering measured and reasonable suggestions on differing ways to present my project. I feel fortunate to have connected with this team, and I highly recommend them! Bravo AutoBizz!!!",
    productType: "enterprise",
    image: "",
    repeatClient: true,
  },
  {
    id: 7,
    username: "investplan1952",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review:
      "AutoBizz team over-delivered! I am beyond thrilled with the final product. They are incredibly knowledgeable and took the time to explain their expert reasoning for their outstanding recommendations. Their response time was prompt, and they were professional throughout this detailed-heavy, voluminous project. It was a delight to have them work on my project, and I will definitely hire them for future automation tasks.",
    productType: "enterprise",
    image: "",
    repeatClient: true,
  },
  {
    id: 8,
    username: "alexandratam",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review: "Final delivery looks great—would recommend!",
    productType: "orders",
    image: "",
    repeatClient: false,
  },
  {
    id: 9,
    username: "mrmaleek",
    country: { name: "Canada", code: "CA" },
    date: "2 years ago",
    rating: 5,
    review:
      "The AutoBizz team worked with me until I was satisfied with the finished product. Thanks again.",
    productType: "inventory",
    image: "",
    repeatClient: true,
  },
  {
    id: 10,
    username: "phildelillo",
    country: { name: "United States", code: "US" },
    date: "2 years ago",
    rating: 5,
    review:
      "The AutoBizz team is very easy and a pleasure to work with. I've been updating them as the project gets refined, and they've been great at offering suggestions and asking good clarifying questions to ensure everything comes together perfectly. 10/10—will be continuing to work with them. Great work.",
    productType: "enterprise",
    image: "",
    repeatClient: true,
  },
  {
    id: 11,
    username: "kapil153",
    country: { name: "United Arab Emirates", code: "AE" },
    date: "2 years ago",
    rating: 5,
    review:
      "Outstanding communication, exceptional professionalism, and the final product is just WOW! #BTW, I will definitely be a repeat customer! The AutoBizz team delivered exactly what they promised, with a hidden surprise. Highly recommended.",
    productType: "enterprise",
    image: "",
    repeatClient: true,
  },
  {
    id: 12,
    username: "lebogner",
    country: { name: "United States", code: "US" },
    date: "3 years ago",
    rating: 5,
    review: "Great work and fast!",
    productType: "products",
    image: "",
    repeatClient: true,
  },
  {
    id: 13,
    username: "pierreledru",
    country: { name: "France", code: "FR" },
    date: "3 years ago",
    rating: 5,
    review: "Très bon service professionnel. Je suis vraiment satisfait.",
    productType: "products",
    image: "",
    repeatClient: true,
  },
  {
    id: 14,
    username: "brandonedesigns",
    country: { name: "United States", code: "US" },
    date: "4 months ago",
    rating: 4.7,
    review:
      "I enjoyed working with the AutoBizz team. They understood the complexity of our project and delivered an exceptional automated solution. I look forward to working with them again on more projects.",
    productType: "enterprise",
    image: "",
    repeatClient: false,
  },
  {
    id: 15,
    username: "patrick_l21",
    country: { name: "Hong Kong", code: "HK" },
    date: "7 months ago",
    rating: 5,
    review: "Well done. Happy client!",
    productType: "enterprise",
    image: "",
    repeatClient: true,
  },
  {
    id: 16,
    username: "dilsroofing",
    country: { name: "United States", code: "US" },
    date: "5 months ago",
    rating: 5,
    review:
      "The AutoBizz team was great to work with every step of the way: communicative, patient, and not afraid to problem-solve when we ran into potential roadblocks.",
    productType: "enterprise",
    image: "",
    repeatClient: false,
  },
  {
    id: 17,
    username: "ahmadrezaj",
    country: { name: "Canada", code: "CA" },
    date: "6 months ago",
    rating: 4.7,
    review:
      "They quickly responded when I requested their services and got on a video call with me to explain what needed to happen with the project. They guided me through every step of the process.",
    productType: "enterprise",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/083d31b53bf299f28c1bc11c0781124a-1619120455302/a91c009a-f09d-4764-9214-a409cb0ed0b3.jpg",
    repeatClient: false,
  },
  {
    id: 18,
    username: "dailinschafer",
    country: { name: "United States", code: "US" },
    date: "9 months ago",
    rating: 5,
    review:
      "The value for money is fantastic. AutoBizz makes it happen 100% if you clearly know what you want. They were also able to improve based on their extensive past experience. 10/10. I will work with them again.",
    productType: "enterprise",
    image: "",
    repeatClient: true,
  },
  {
    id: 19,
    username: "choudhury90",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review: "Amazing skills. Great communication and understanding!",
    productType: "enterprise",
    image: "",
    repeatClient: true,
  },
  {
    id: 20,
    username: "kevinfeucht456",
    country: { name: "Spain", code: "ES" },
    date: "1 year ago",
    rating: 5,
    review: "Excellent work, as requested.",
    productType: "products",
    image: "",
    repeatClient: true,
  },
  {
    id: 21,
    username: "kevinfeucht456",
    country: { name: "Spain", code: "ES" },
    date: "1 year ago",
    rating: 5,
    review: "Amazing service!",
    productType: "orders",
    image: "",
    repeatClient: true,
  },
  {
    id: 22,
    username: "a_groz",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review:
      "The AutoBizz team has been patient, accommodating, and very skilled with the work they did! Very satisfied with the results and the extra time they took to make sure I got exactly what I needed. Fantastic job!",
    productType: "enterprise",
    image: "",
    repeatClient: true,
  },
  {
    id: 23,
    username: "manifestsource",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review:
      "This team was FANTASTIC to work with! I highly recommend their services. They were quick to respond, sensitive to my timeline, and very responsive to my questions and requests as we worked through the project. I will continue to use their services!",
    productType: "enterprise",
    image: "",
    repeatClient: true,
  },
  {
    id: 24,
    username: "walkertexas",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review:
      "Very good and fast. They fixed and improved an existing file that I had.",
    productType: "inventory",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/ae3ffc49ba532b163caba953da08ba3c-1703930951008/cd05457a-b7bf-404c-b4f5-d701eb78ba99.jpg",
    repeatClient: false,
  },
  {
    id: 25,
    username: "nummusnetwork",
    country: { name: "United Kingdom", code: "GB" },
    date: "2 years ago",
    rating: 5,
    review:
      "AutoBizz delivered within hours, but due to a miscommunication on my part, they quickly redid the project to give me exactly what I wanted. Judging by my results, if you need anything workflow or spreadsheet automation related, you're in good hands. Highly recommended A++++.",
    productType: "enterprise",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/a81d99fff1e0c9ed91a489426ac324e6-1682502131877/9aba6f2f-70ae-4f69-b964-373b034dcad6.jpg",
    repeatClient: true,
  },
  {
    id: 26,
    username: "zomidar",
    country: { name: "United Arab Emirates", code: "AE" },
    date: "2 years ago",
    rating: 5,
    review:
      "They are a very skilled and efficient team for finance and account modeling.",
    productType: "enterprise",
    image: "",
    repeatClient: false,
  },
  {
    id: 27,
    username: "gzac100",
    country: { name: "United States", code: "US" },
    date: "2 years ago",
    rating: 5,
    review: "Top-notch service!",
    productType: "enterprise",
    image: "",
    repeatClient: true,
  },
  {
    id: 28,
    username: "foreside",
    country: { name: "United States", code: "US" },
    date: "2 years ago",
    rating: 4.7,
    review:
      "The project was to find the concurrent calls from a downloaded call log. The AutoBizz team was communicative, ensured they understood the desired outcome, and delivered a quick solution.",
    productType: "enterprise",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/091be4c1c507b039f343fed3ef6b5a1f-1550678288098/30fb74bb-70dd-4b2d-afdd-a27f3999c0fd.png",
    repeatClient: false,
  },
  {
    id: 29,
    username: "gzac100",
    country: { name: "United States", code: "US" },
    date: "2 years ago",
    rating: 5,
    review:
      "Excellent service. Very professional and knowledgeable. Delivers what they promise. Great to work with.",
    productType: "enterprise",
    image: null,
    repeatClient: true,
  },
  {
    id: 30,
    username: "bd_anna88",
    country: { name: "Australia", code: "AU" },
    date: "2 years ago",
    rating: 5,
    review:
      "Highly recommend them! The AutoBizz team is very skilled and reliable. I'll definitely be working with them again.",
    productType: "orders",
    image: null,
    repeatClient: true,
  },
  {
    id: 31,
    username: "bd_anna88",
    country: { name: "Australia", code: "AU" },
    date: "2 years ago",
    rating: 5,
    review:
      "Very skilled, know what they're doing! Will work with the AutoBizz team again.",
    productType: "inventory",
    image: null,
    repeatClient: true,
  },
  {
    id: 32,
    username: "bd_anna88",
    country: { name: "Australia", code: "AU" },
    date: "2 years ago",
    rating: 5,
    review:
      "Great skills, very fast, delivered per requirements. Highly recommend the AutoBizz team!",
    productType: "products",
    image: null,
    repeatClient: true,
  },
  {
    id: 33,
    username: "oscararellano",
    country: { name: "United States", code: "US" },
    date: "2 years ago",
    rating: 5,
    review: "Great job, great communication, 100% recommended!",
    productType: "inventory",
    image: null,
    repeatClient: true,
  },
  {
    id: 34,
    username: "oscararellano",
    country: { name: "United States", code: "US" },
    date: "2 years ago",
    rating: 5,
    review: "Great team to work with, 100% recommended!",
    productType: "products",
    image: null,
    repeatClient: true,
  },
  {
    id: 35,
    username: "bijoychandra",
    country: { name: "India", code: "IN" },
    date: "2 years ago",
    rating: 5,
    review:
      "Working with the AutoBizz team for the last year... They are a team you can blindly trust. Highly recommended for long-term business. Very rare to find this type of IT service in the industry.",
    productType: "enterprise",
    image: null,
    repeatClient: true,
  },
  {
    id: 36,
    username: "grow_dokotela",
    country: { name: "Australia", code: "AU" },
    date: "2 years ago",
    rating: 5,
    review:
      "The AutoBizz team has exceptional communication skills, ensuring the job is done to the customer’s satisfaction. Very efficient and accurate. Thanks again!",
    productType: "enterprise",
    image: null,
    repeatClient: true,
  },
  {
    id: 37,
    username: "kelvinmutwir156",
    country: { name: "Kenya", code: "KE" },
    date: "2 years ago",
    rating: 5,
    review:
      "Good communication skills and excellent knowledge of spreadsheet automation and workflows.",
    productType: "inventory",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/73a31d6298c27eb19c31138045ca5ed5-1699823742372/e1eae556-f150-4b85-8f45-bb0a295ce771.jpg",
    repeatClient: false,
  },
  {
    id: 38,
    username: "herbloom",
    country: { name: "United States", code: "US" },
    date: "2 years ago",
    rating: 5,
    review:
      "The AutoBizz team was very fast with communication and even provided a direction video so that I can understand how to use the automated solution. I will work with them again.",
    productType: "products",
    image: null,
    repeatClient: false,
  },
  {
    id: 39,
    username: "grow_dokotela",
    country: { name: "Australia", code: "AU" },
    date: "2 years ago",
    rating: 5,
    review:
      "Very prompt service, with excellent communication. Thank you so much!",
    productType: "enterprise",
    image: null,
    repeatClient: true,
  },
  {
    id: 40,
    username: "adriel1712",
    country: { name: "United States", code: "US" },
    date: "3 years ago",
    rating: 5,
    review:
      "Super reliable team! They provided shortcuts that make life so much easier!",
    productType: "orders",
    image: null,
    repeatClient: false,
  },
  {
    id: 41,
    username: "kerildesigns",
    country: { name: "United States", code: "US" },
    date: "3 years ago",
    rating: 5,
    review:
      "The AutoBizz team was very accessible and prompt. They answered all my questions and went the extra mile. Very professional to work with, and we're already mapping out our next projects. Highly recommend them!",
    productType: "enterprise",
    image: null,
    repeatClient: true,
  },
  {
    id: 42,
    username: "kbobbyfashion",
    country: { name: "United States", code: "US" },
    date: "3 years ago",
    rating: 5,
    review:
      "Great job! Fast and efficient. Thank you. I will definitely use your services again.",
    productType: "orders",
    image: null,
    repeatClient: false,
  },
  {
    id: 43,
    username: "pierreledru",
    country: { name: "France", code: "FR" },
    date: "3 years ago",
    rating: 5,
    review:
      "Great! I highly recommend them. The job was perfect and completed very quickly. The AutoBizz team did everything needed to ensure I was happy as a customer. HIGHLY RECOMMEND! Génial, je recommande le travail est parfait et très rapide. L'équipe a fait TOUT CE QUI DOIT ETRE FAIT pour que le client (moi !) soit satisfait. JE RECOMMANDE VIVEMENT.",
    productType: "enterprise",
    image: null,
    repeatClient: true,
  },
  {
    id: 44,
    username: "zowika",
    country: { name: "Netherlands", code: "NL" },
    date: "3 years ago",
    rating: 5,
    review: "They did a great job.",
    productType: "products",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/profile/photos/4135380/original/1417206701591_facebook20141128-13542-11im1a5.jpg",
    repeatClient: true,
  },
  {
    id: 45,
    username: "lebogner",
    country: { name: "United States", code: "US" },
    date: "3 years ago",
    rating: 5,
    review: "WOW! Super good service and fast work.",
    productType: "enterprise",
    image: null,
    repeatClient: true,
  },
  {
    id: 46,
    username: "perrym521",
    country: { name: "United Kingdom", code: "GB" },
    date: "3 years ago",
    rating: 5,
    review:
      "Excellent working with the AutoBizz team. They are very hardworking, thorough, and went the extra mile. I will definitely be using their services in the future for any workflow automation needs.",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 47,
    username: "zowika",
    country: { name: "Netherlands", code: "NL" },
    date: "3 years ago",
    rating: 5,
    review:
      "The AutoBizz team has done an outstanding job. We've already planned our next project together. 10/10 would recommend to anyone. Good communication, highly skilled, and fast-paced.",
    productType: "orders",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/profile/photos/4135380/original/1417206701591_facebook20141128-13542-11im1a5.jpg",
    repeatClient: true,
  },
  {
    id: 48,
    username: "tanmuhtaroff",
    country: { name: "Bulgaria", code: "BG" },
    date: "3 years ago",
    rating: 5,
    review:
      "Very quick and reliable. They completed work that was supposed to take 3 days in just 24 hours at a fair price. I definitely recommend their service!",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 49,
    username: "pieperpost",
    country: { name: "Netherlands", code: "NL" },
    date: "4 months ago",
    rating: 5,
    review:
      "This is the second time working with the AutoBizz team. I can recommend them to anyone!",
    productType: "orders",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/adc31ab466013f70d679bc0cc8d0ce87-1363789091705869785813/JPEG_20240121_214305_694786491309636732.jpg",
    repeatClient: true,
  },
  {
    id: 50,
    username: "maicolbruno",
    country: { name: "Canada", code: "CA" },
    date: "9 months ago",
    rating: 5,
    review:
      "The AutoBizz team was great to work with. They provided possible workflows and solutions to the problem. They ensured I was satisfied and happy with the support provided. Very professional and practical meeting!",
    productType: "orders",
    image: null,
    repeatClient: false,
  },
  {
    id: 51,
    username: "chrissarraf",
    country: { name: "United States", code: "US" },
    date: "9 months ago",
    rating: 5,
    review:
      "Excellent communication and fully capable of handling everything I asked for. Wonderful work!",
    productType: "orders",
    image: null,
    repeatClient: false,
  },
  {
    id: 52,
    username: "nassau",
    country: { name: "United States", code: "US" },
    date: "10 months ago",
    rating: 5,
    review: "Thank you for your support.",
    productType: "orders",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/profile/photos/1908090/original/avatar.jpg",
    repeatClient: false,
  },
  {
    id: 53,
    username: "pieperpost",
    country: { name: "Netherlands", code: "NL" },
    date: "10 months ago",
    rating: 5,
    review:
      "This was a complicated project with lots of customizations. In the end, it took a month instead of 8 days, but the AutoBizz team corrected every single issue until everything worked perfectly. Very satisfied with the result.",
    productType: "orders",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/adc31ab466013f70d679bc0cc8d0ce87-1363789091705869785813/JPEG_20240121_214305_694786491309636732.jpg",
    repeatClient: true,
  },
  {
    id: 54,
    username: "darrenfenton",
    country: { name: "United Kingdom", code: "GB" },
    date: "10 months ago",
    rating: 5,
    review: "Great job done!",
    productType: "orders",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/161541f34a9d55b4c3f4385b6dba5946-1681592818137/82e2d94a-f5cd-4724-b7b1-3444ad798bdc.jpg",
    repeatClient: false,
  },
  {
    id: 55,
    username: "estebanmontesin",
    country: { name: "Spain", code: "ES" },
    date: "3 years ago",
    rating: 5,
    review: "Great work. Really useful.",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 56,
    username: "humanresourceso",
    country: { name: "Philippines", code: "PH" },
    date: "3 years ago",
    rating: 5,
    review:
      "The AutoBizz team is smart, hardworking, and trustworthy. Looking forward to working with them in the future!",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 57,
    username: "estebanmontesin",
    country: { name: "Spain", code: "ES" },
    date: "3 years ago",
    rating: 5,
    review: "Very nice and easy to work with. Highly recommendable.",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 58,
    username: "humanresourceso",
    country: { name: "Philippines", code: "PH" },
    date: "3 years ago",
    rating: 5,
    review:
      "Great team, very creative, and excellent problem solvers! A pleasure to work with. A++",
    productType: "enterprise",
    image: null,
    repeatClient: true,
  },
  {
    id: 59,
    username: "stin212",
    country: { name: "United States", code: "US" },
    date: "3 years ago",
    rating: 5,
    review:
      "The AutoBizz team was amazing to work with. They went above and beyond what was needed and spent much more time than originally discussed. They make sure your project meets your standards and are very honest as well!",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 60,
    username: "michaellmarx",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review:
      "The AutoBizz team is personable and helpful as technical consultants. I would use them in the future.",
    productType: "inventory",
    image: null,
    repeatClient: false,
  },
  {
    id: 61,
    username: "protein_com",
    country: { name: "Sweden", code: "SE" },
    date: "1 year ago",
    rating: 5,
    review:
      "Just perfect. I am confident I will work more with the AutoBizz team in the future.",
    productType: "orders",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/be24024c3faa8743fbc221538901eaba-1666706150857/e7ec9776-397b-465b-89c7-63ea899bf1d6.jpeg",
    repeatClient: false,
  },
  {
    id: 62,
    username: "garethstageman",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review:
      "Excellent work. The team was highly responsive and delivered exactly what I needed. Changes were implemented quickly and accurately during the project. Communication was friendly and professional. I have already commissioned more work and hope to collaborate with the team long-term. Highly recommended!",
    productType: "inventory",
    image: null,
    repeatClient: false,
  },
  {
    id: 63,
    username: "jakerosen614",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review: "Great and easy to work with.",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 64,
    username: "rudylion72",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review: "Exceptional order delivery, exactly as promised.",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 65,
    username: "galih_setyasa",
    country: { name: "Indonesia", code: "ID" },
    date: "1 year ago",
    rating: 5,
    review:
      "I had the pleasure of working with the AutoBizz team to automate a time-consuming task. Their expertise in spreadsheet automation and understanding of the assignment were impressive. They completed work that would have taken me two days in just 1–2 hours. They were trustworthy with confidential tasks, easy to communicate with, and highly professional. Highly recommended for future assignments!",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 66,
    username: "kevinfeucht455",
    country: { name: "Spain", code: "ES" },
    date: "1 year ago",
    rating: 5,
    review:
      "The AutoBizz team is amazing, with exceptional skill sets. They created the sheet exactly how I envisioned. Thank you so much!",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 67,
    username: "lamacabra",
    country: { name: "Spain", code: "ES" },
    date: "1 year ago",
    rating: 5,
    review:
      "The team is highly professional! Delivered excellent work on time.",
    productType: "orders",
    image: null,
    repeatClient: false,
  },
  {
    id: 68,
    username: "investplan1952",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review:
      "I feel incredibly lucky to have had such a professional and capable team work on my project. They offered measured advice, responded promptly, and ensured seamless collaboration. I will definitely hire them again and 1000% recommend them to everyone!",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 69,
    username: "cindyl724",
    country: { name: "Canada", code: "CA" },
    date: "1 year ago",
    rating: 5,
    review: "Great service with a clear understanding of my needs.",
    productType: "products",
    image: null,
    repeatClient: false,
  },
  {
    id: 70,
    username: "lamacabra",
    country: { name: "Spain", code: "ES" },
    date: "1 year ago",
    rating: 5,
    review:
      "Wonderful experience and exceptional work delivered by the AutoBizz team.",
    productType: "orders",
    image: null,
    repeatClient: true,
  },
  {
    id: 71,
    username: "manifestsource",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review:
      "Another outstanding experience with the AutoBizz team! I highly recommend them; they have become a consistent resource for the work we need completed. They always find solutions to complex Spreadsheet automation and data visualization challenges. We'll continue to rely on their exceptional services time and time again.",
    productType: "enterprise",
    image: null,
    repeatClient: true,
  },
  {
    id: 72,
    username: "matthew161",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review:
      "The AutoBizz team was great to work with. They listened closely to exactly what I needed and were highly responsive. The work came out exactly how I wanted.",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 73,
    username: "cindyl724",
    country: { name: "Canada", code: "CA" },
    date: "1 year ago",
    rating: 5,
    review:
      "Excellent service from the AutoBizz team. I’ll be requesting another job from them soon!",
    productType: "orders",
    image: null,
    repeatClient: true,
  },
  {
    id: 74,
    username: "phildelillo",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review:
      "The AutoBizz team is honestly one of the best in terms of willingness to collaborate and work with you to reach the ultimate goal. When I wasn’t exactly sure how to achieve one of the desired outcomes, they were phenomenal in helping figure out both the ‘what’ and the ‘how’ to get us there. Cannot recommend them enough!",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 75,
    username: "a_groz",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review: "Excellent job – everything turned out great!",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 76,
    username: "freddianat",
    country: { name: "Canada", code: "CA" },
    date: "1 year ago",
    rating: 5,
    review:
      "The AutoBizz team was very helpful. They went above and beyond and gave me exactly what I needed.",
    productType: "enterprise",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/8a71d584ec3b88007c85021aedf49408-1509838232138/5c0e9fdb-d15f-4d2f-a0c3-7f35cc4f2303.jpg",
    repeatClient: false,
  },
  {
    id: 77,
    username: "kingtee23",
    country: { name: "United Kingdom", code: "GB" },
    date: "1 year ago",
    rating: 5,
    review:
      "Excellent service – they solved a significant issue, saving me a lot of future time. Good work!",
    productType: "orders",
    image:
      "https://fiverr-res.cloudinary.com/image/upload/f_auto,q_auto,t_profile_small/v1/attachments/profile/photo/1e87a538820a79f7a0558a7c6409b3f1-795292681604402577470/JPEG_20201103_112253_2193377567639132687.jpg",
    repeatClient: false,
  },
  {
    id: 78,
    username: "investplan1952",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review:
      "I worked with the AutoBizz team recently, and they overdelivered once again! Their continued attention to detail and offering expert advice on what would make the final document ideal is an invaluable business skill. It was a professional collaborative effort, and I am beyond thrilled with the final document!",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 79,
    username: "manifestsource",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review:
      "Another fabulous and timely delivery! I appreciate their professional communication and Spreadsheet automation skills. They are making my life much easier. I highly recommend their services and will continue to use them in the very near future.",
    productType: "enterprise",
    image: null,
    repeatClient: true,
  },
  {
    id: 80,
    username: "lana_bauer",
    country: { name: "Denmark", code: "DK" },
    date: "1 year ago",
    rating: 5,
    review:
      "The AutoBizz team was very perceptive and attentive. They helped me find the best solution and delivered the product on time and according to my best expectations. Thank you!",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 81,
    username: "mruizjr",
    country: { name: "United States", code: "US" },
    date: "1 year ago",
    rating: 5,
    review: "Great experience! I will definitely purchase services again!",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
  {
    id: 82,
    username: "grow_dokotela",
    country: { name: "Australia", code: "AU" },
    date: "1 year ago",
    rating: 5,
    review:
      "The AutoBizz team was great to work with and extremely responsive throughout the project. They go above and beyond and pay close attention to detail. I will definitely use their services again in the future.",
    productType: "enterprise",
    image: null,
    repeatClient: false,
  },
];
export default ProductReviewsData;
